### ISSUE TITLE
Having trouble with your examples

### ISSUE THREAD

**Issue by lmforget** [mindcrypt/powerglot#2]
I read your talk from Dec and I wanted to try it myself. I was hoping to use your tool to do a live demo for my boss.

In my attempt, I am using a VM with Ubuntu 20.04.1. The version of Python is 3.8.5. I added numpy.

I can run with -o and create a new JPEG but embedded payload will not work, I tried your shell code and PowerShell scripts with the cat.jpeg. Furthermore -d does not detect anything in the examples nor the generated files.

I used feh to confirm the jpeg part does work.

What am I doing wrong?

**Comment by mindcrypt** [comment]
Hello,
Can you send me the exact parameters you are using? What is the size of the file you want to hide?
Thank you,
Alfonso

**Comment by lmforget** [comment]
python3 powerglot.py -o test.sh cat.jpeg cat-test.jpeg

test.sh is from your examples folder - 11 bytes
ls;whoami;

cat.jpeg is from your repo as well.

i ran
python3 powerglot.py -d ./ and it did not detect the polyglot in your examples nor my new file cat-test.jpeg

**Comment by mindcrypt** [comment]
Hello, my friend,
I am working to incorporate rules for the detection of polyglots in different formats. Currently, only the presence of StegoSploit is detected in JPEG files (added */ --> after FFD9)
Thanks,

**Comment by lmforget** [comment]
I figured my problem with the first part related to generating a polyglot using your tool :)

I suggest adding exit to your scripts for example test.sh would be now be
ls;whoami;exit;

This eliminates the error messages generated when bash tries to process the remaining bytes of the file following the script.

Thanks.
